### ISSUE TITLE
Repeats the "this pr is too big" message

### ISSUE THREAD

**Issue by TheTechRobo** [CodelyTV/pr-size-labeler#19]
whenever i push it repeats it. really annoying as i keep getting notifications for nothing.

**Comment by JavierCane** [comment]
Hi!

As hoy can see in [this example](https://github.com/CodelyTV/pr-size-labeler/pull/14), it publishes the mentioned comment one time for each Workflow execution. That is, it depends on your `on` clause configuration ([example](https://github.com/CodelyTV/pr-size-labeler/blob/master/.github/workflows/labeler.yml#L3)).

Could you please link or attach your yaml configuration and a screenshot of the duplicated message in a PR? (Wipe out sensible information if that's the case)

This could help debugging or reproducing the issue 🙂

Thanks!

**Comment by TheTechRobo** [comment]
```
name: labeler

on: [pull_request]

jobs:
  labeler:
    runs-on: ubuntu-latest
    name: Label the PR size
    steps:
      - uses: codelytv/pr-size-labeler@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          xs_max_size: '10'
          s_max_size: '100'
          m_max_size: '500'
          l_max_size: '1000'
          fail_if_xl: 'false'
          message_if_xl: 'This PR is extremely big! Please, split it 😊'
```
![image](https://user-images.githubusercontent.com/52163910/90407666-becaa080-e074-11ea-8a5e-ba53beebc29f.png)
