### ISSUE TITLE
Duplicated labels when PR is updated

### ISSUE THREAD

**Issue by Shudy** [CodelyTV/pr-size-labeler#32]
When a PR is updated with a commit and the number of modified lines changes, the GHAction applies the label to the PR, however it does not remove the old label and adds the new label of the corresponding size.

Actually the action is quite simple:
```
on:
  pull_request:
jobs:
  tag_pr_size:
    runs-on: ubuntu-latest
    name: Label the PR size
    steps:
      - uses: codelytv/pr-size-labeler@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          xs_max_size: '10'
          s_max_size: '30'
          m_max_size: '100'
          l_max_size: '500'
          message_if_xl: >
            'This PR exceeds the recommended size of 500 lines.
            Please make sure you are NOT addressing multiple issues with one PR.’
```

Examples:

name: Label PR Size
<img width="714" alt="Captura de pantalla 2021-10-19 a las 16 08 39" src="https://user-images.githubusercontent.com/1649101/137927347-6a70e2fc-ebb4-4bc3-9d1c-1768b35b4301.png">

<img width="812" alt="Captura de pantalla 2021-10-19 a las 16 09 04" src="https://user-images.githubusercontent.com/1649101/137927878-712c164d-2f37-440f-9712-43e46fd4ea6d.png">

Thanks for the work!
