### ISSUE TITLE
Subtle bug 🔥 in support for ignoring files !?

### ISSUE THREAD

**Issue by favmd** [CodelyTV/pr-size-labeler#37]
Dear @rgomezcasas

thanks for testing, refactoring and merging my feature pr #33 (based on issue #9) 👍 

But I do think that one of your changes might have added a very subtle bug.

See this code in main:

https://github.com/CodelyTV/pr-size-labeler/blob/88ab4d8199ba00e6ea8da944e59453ea7e2c6ca4/src/github.sh#L19-L27

compared to my original version:

```sh
    local changes=0


    for file in $(echo "$body" | jq -r '.[] | @base64'); do
      _jq() {
        echo "$file" | base64 -d | jq -r "$1"
      }
      local ignore_file=0 # False
      for file_to_ignore in $files_to_ignore; do
        if [ "$file_to_ignore" = "$(basename $(_jq '.filename'))" ]; then
          ignore_file=1 # True
        fi
      done
      if [ $ignore_file -eq 0 ]; then
        ((changes += $(_jq '.changes')))
      fi
    done
```

The difference I want to point at is on line 22:

https://github.com/CodelyTV/pr-size-labeler/blob/88ab4d8199ba00e6ea8da944e59453ea7e2c6ca4/src/github.sh#L22

**Does this work for `files_to_ignore` lists with more than one filename?**

Let's say that `files_to_ignore` = `'Pipfile.lock package-lock.json'`

and you change your `package-lock.json`.

1. Your code would check if `Pipfile.lock` != `package-lock.json` ?
2. Yes, it is! Count the changes! ~> Err, that's not what we want 🔥 

That's why you will have to loop over all filenames all the time.

Note 👉 I **haven't** tested this, just compared your code to mine and this seemed like a real logical difference.

If you can confirm this, let's do a `v1.8.1` asap 🚀

**Comment by favmd** [comment]
Thank you @szamanr for verifying this 👍 

You're right, it gets even worse with longer lists, counting the changes multiple times.

**Comment by danielmklein** [comment]
I am not sure if what we are seeing is the same issue or a different issue, but with 1.8.0 our labeling stopped working completely. Rolling back to 1.7.0 fixed things. Here is our job:
```yaml
    label_size:
        runs-on: ubuntu-latest
        name: Label the PR size
        steps:
            - uses: codelytv/pr-size-labeler@v1.7.0
              with:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  xs_label: 'size/xs'
                  xs_max_size: '10'
                  s_label: 'size/s'
                  s_max_size: '100'
                  m_label: 'size/m'
                  m_max_size: '500'
                  l_label: 'size/l'
                  l_max_size: '1000'
                  xl_label: 'size/xl'
                  fail_if_xl: 'false'
                  message_if_xl: >
                      'Wow, this is a big boi! How might be break something like this into smaller pieces next time?'
                  github_api_url: 'api.github.com'
```

Could this be due to us not passing `files_to_ignore` at all?
