### ISSUE TITLE
Label is not added pull requests

### ISSUE THREAD

**Issue by sukki37** [CodelyTV/pr-size-labeler#43]
This my pr action link, https://github.com/sukkiCat/test/pull/1, no error logs, but labels are not added.

**Comment by JuanDavidBuitrago** [comment]
Hi @sukki37, did you manage to solve this problem? I have the same problem.

**Comment by johnlk** [comment]
You'll need to add a github action yml file to the project. Here's an example `.github/labeler.yml`.
```yml
name: labeler

on: [pull_request]

jobs:
  labeler:
    runs-on: ubuntu-latest
    name: Label the PR size
    steps:
      - uses: codelytv/pr-size-labeler@v1.8.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          files_to_ignore: |
            "README.md"
            "static/*"
            "conftest.py"
            "pyproject.toml"
```
