### ISSUE TITLE
Feature Request: Regular expression support for files_to_ignore parameter

### ISSUE THREAD

**Issue by Alton09** [CodelyTV/pr-size-labeler#45]
It would be great if user's could include a regular expression for the `files_to_ignore` parameter. For example if you wanted to exlclude test classes from the size counting you could add something like this...
```.yml
files_to_ignore: '*Test*'
```

**Comment by mediamartin** [comment]
This seems the same issue;

https://github.com/CodelyTV/pr-size-labeler/issues/38

**Comment by wundo** [comment]
@mediamartin #50 did not fix this issue :(

**Comment by jmfennell** [comment]
Is there an update on when #50 is going to be released?

**Comment by mipierre** [comment]
Poking if theres plan for a new release that includes https://github.com/CodelyTV/pr-size-labeler/pull/50 ?

**Comment by Aavache** [comment]
FYI, you can refer to the specific commit where https://github.com/CodelyTV/pr-size-labeler/pull/50 was implemented in your workflow:

```yml
jobs:
  labeler:
    runs-on: ubuntu-latest
    name: Label the PR size
    steps:
      - uses: codelytv/pr-size-labeler@d269449310fe33526c56b2dfe6244e3a9f489b15
```

Once this is applied, the regex seems to work fine for me :)
