### ISSUE TITLE
Document required permissions

### ISSUE THREAD

**Issue by adrianjost** [CodelyTV/pr-size-labeler#47]
It took me a bit of time to figure out which [permissions](https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs#overview) this actions needs.

In my case, adding the following worked. Maybe that should be added to the README.

```yml
jobs:
  labeler:
    ...
    permissions:
      issues: write
      pull-requests: write
    steps:
      ...
```
