### ISSUE TITLE
Labeling nonexist size level `size/xs`

### ISSUE THREAD

**Issue by waynexia** [CodelyTV/pr-size-labeler#60]
## Desc

I removed the default `size/xs` level, and my config rule starts from `S`. But it still gives the `size/xs` to PR

## Info

workflow: https://github.com/GreptimeTeam/greptimedb/actions/runs/6584684983/job/17889694460?pr=2631

action output:
```plaintext
This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Total modifications (additions + deletions): 7
Ignoring files (if present): Cargo.lock
Labeling pull request with size/xs
Final labels: "size/xs"
```
config file:
```yml
name: size-labeler

on: [pull_request]

jobs:
  labeler:
    runs-on: ubuntu-latest
    name: Label the PR size
    steps:
      - uses: codelytv/pr-size-labeler@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          s_label: 'Size: S'
          s_max_size: '100'
          m_label: 'Size: M'
          m_max_size: '500'
          l_label: 'Size: L'
          l_max_size: '1000'
          xl_label: 'Size: XL'
          fail_if_xl: 'false'
          message_if_xl: >
            This PR exceeds the recommended size of 1000 lines.
            Please make sure you are NOT addressing multiple issues with one PR.
            Note this PR might be rejected due to its size.
          github_api_url: 'api.github.com'
          files_to_ignore: 'Cargo.lock'
```
