### ISSUE TITLE
Question: Does this action work with pull requests from forks?

### ISSUE THREAD

**Issue by alexearnshaw** [CodelyTV/pr-size-labeler#8]
Hi, I'm looking for an app or action to label pull requests with a size based on LOC. This action looks perfect, but another similar action I tried did not work on PRs created from forks (which is the majority of PRs in our project). Can you confirm if this action will work on PRs from forks?

**Comment by rgomezcasas** [comment]
It works! But if it's a fork you need to do some changes.

> I'll change the README to reflect it (I'll close this issue when this is done). But for now:

If it's a fork you can't use the `secrets.GITHUB_TOKEN` because this belongs only to your project, so a fork won't have access to it.
To be able to use it, you should create a custom token from a user of your organization (usually you create a "bot" user for it, like [ours](https://github.com/codelytv-bot)) and then add this token to your repository secrets (usually with a `GITHUB_BOT_TOKEN` name or similar).

So, instead of having something like:
```yml
steps:
    - uses: codelytv/pr-size-labeler@v1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

You'll have:
```yml
steps:
    - uses: codelytv/pr-size-labeler@v1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_BOT_TOKEN }}
```

If you don't want to create a new user you can create a personal token from any member of your organization. But then on every pull request, when autolabeled, instead of "github-bot have added some label" you'll have "This user has added some label".

I guess it's the same problem you have with other Actions, the solution it's the same for everyone. 😊
