### ISSUE TITLE
Add support for ignoring files, such as package-lock.json

### ISSUE THREAD

**Issue by kevindice** [CodelyTV/pr-size-labeler#9]

**Comment by dowrow** [comment]
I'm really interested in this. What would be the best way to implement it? 
I've been checking the github::calculate_total_modifications() method and the Github API docs and the only approach I found would be:
- Allow a 8th argument to be passed to the action (ignore_files), which would be a string with the comma-separated files to ignore.
- Inside calculate_total_modifications() define a variable totalLines = deteledLines + addedLines (current returned value)
- Loop over every file in the PR (using the endpoint GET /repos/:owner/:repo/pulls/:pull_number/files) and check if the filename matches one of the ignored_files. If it does, substract its (deletedLines + addedLines) from the totalLines.

**Comment by JavierCane** [comment]
It would be awesome to support this 🙌

@dowrow, your approach seems to completely make sense 🙂

The only thing I would suggest would be using a [YAML sequence](https://yaml.org/spec/1.2/spec.html#id2790320) instead of a comma separated string for specifying the different files to ignore. That is, being able to specify it as `files_to_ignore: ['package-lock.json', 'composer.lock']` instead of `files_to_ignore: 'package-lock.json, composer.lock'`.

Example of how the `README.md` complete example would look like:

```yml
name: labeler

on: [pull_request]

jobs:
  labeler:
    runs-on: ubuntu-latest
    name: Label the PR size
    steps:
      - uses: codelytv/pr-size-labeler@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          xs_max_size: '10'
          s_max_size: '100'
          m_max_size: '500'
          l_max_size: '1000'
          fail_if_xl: 'false'
          message_if_xl: 'This PR is so big! Please, split it 😊'
          files_to_ignore: ['package-lock.json', 'composer.lock']
```

What do you think?
