### ISSUE TITLE
Actions fails unless GITHUB_TOKEN is explicitly provided

### ISSUE THREAD

**Issue by manio143** [CodelyTV/pr-size-labeler#92]
I've a good hour trying to debug why the action was failing for my repo. Turns out the GITHUB_TOKEN value was blank.
By default the action uses `github.token` which is empty. Instead `secrets.GITHUB_TOKEN` needs to be used.
https://github.com/CodelyTV/pr-size-labeler/blob/1c3422395d899286d5ee2c809fd5aed264d5eb9b/action.yml#L4-L7

Also would be good to check for that in the script, because it runs all the way, but `jq` fails to parse response from GitHub API when it's not in an expected format. It fails but the script isn't aware why and doesn't print anything that could point to an authorization issue.

Work around:
```yaml
steps:
- uses: codelytv/pr-size-labeler@v1
  with:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
